os:
    - linux
    - osx

env:
    global:
        - PACKAGE="Vintageous"
    matrix:
        - SUBLIME_TEXT_VERSION="3"

before_install:
    - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/travis.sh

install:
    - sh travis.sh bootstrap

script:
    - sh travis.sh run_tests

notifications:
    email: false
