language: python
python:
    # this has nothing to do with ST 2/ ST 3, just leave it as 2.7
    - "2.7"

env:
    global:
        # Your package name
        - PACKAGE="Vintageous"
    matrix:
        - SUBLIME_TEXT_VERSION="3"

before_install:
    - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/travis.sh

install:
    - sh travis.sh bootstrap

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
    - sh travis.sh run_tests

notifications:
    email: false
